# Hello word with ubuntu based image

FROM ubuntu:18.04
MAINTAINER fabio.oliveira.sales@gmail.com
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y vim
CMD ["echo", "Hello Word"]


